/**
 * Bagel Bazaar Monroe — menu images from uploaded /data folder
 * Regenerate: node scripts/map-data-images.mjs
 */
(function () {
  const W = 640;
  const H = 512;
  const CACHE_VERSION = 3;
  const PLACEHOLDER = "data/Bagel (1).jpg";

  const IMAGE_MAP = {
  "coffee-drip": "data/coffee.jpg",
  "espresso-single": "data/SingleEspresso.jpg",
  "espresso-double": "data/Double Espresso.jpg",
  "cappuccino-hot": "data/Hot Cappuccino.jpg",
  "cappuccino-flavored": "data/FlavoredHotCappuccino.jpg",
  "latte-iced": "data/IcedLatte.jpg",
  "latte-iced-flavored": "data/FlavoredIcedLatte.jpg",
  "coffee-iced": "data/IcedCoffee.jpg",
  "coffee-iced-flavored": "data/FlavoredIcedCoffee.jpg",
  "frappe-frozen": "data/FrozenFrappe.jpg",
  "frappe-flavored": "data/Flavored Frozen Frappe.jpg",
  "box-o-joe": "data/Box o Joe (12 Cups).jpg",
  "bagel-1": "data/Bagel (1).jpg",
  "bagels-6": "data/Bagels (6).jpg",
  "bagels-13": "data/Bagel (13).jpg",
  "bagel-special-1": "data/#1 Bagel Special.jpg",
  "bagel-special-2": "data/#2 Bagel Special.jpg",
  "spread-butter": "data/Bagel w Butter.jpg",
  "spread-cinna-butter": "data/Bagel w Cinna Butter.jpg",
  "spread-peanut-butter": "data/Bagel w Peanut Butter.jpg",
  "spread-nutella": "data/Bagel w Nutella.jpg",
  "spread-jelly": "data/Bagel w Jelly.jpg",
  "spread-plain-cc": "data/bagel with plain cream cheese.jpg",
  "spread-veggie-cc": "data/Vegetable Cream Cheese.jpg",
  "spread-scallion-cc": "data/Bagel w Scallion Cream Cheese.jfif",
  "spread-lox-spread": "data/bagel with lox spread.jpg",
  "spread-walnut-cc": "data/Bagel w Walnut Raisin Cream Cheese.jfif",
  "spread-strawberry-cc": "data/Bagel w Strawberry Cream Cheese.jfif",
  "spread-jalapeno-cc": "data/Bagel w Jalapeno Garlic Cream Cheese.jfif",
  "spread-oreo-cc": "data/Bagel w Oreo Explosion Cream Cheese.jfif",
  "spread-bacon-cc": "data/Bagel w Bacon & Chives Cream Cheese.jfif",
  "spread-lite-veggie-cc": "data/Bagel w Lite Veggie Cream Cheese.jfif",
  "spread-olive-cc": "data/Bagel w Green Olive Pimento Cream Cheese.jfif",
  "lox-plain-cc": "data/Bagel w Lox & Plain Cream Cheese.jfif",
  "lox-veggie-cc": "data/Bagel w Lox & Veggie Cream Cheese.jfif",
  "lox-scallion-cc": "data/Bagel w Lox & Scallion Cream Cheese.jfif",
  "lox-whitefish": "data/Bagel w Whitefish Salad & Plain Cream Cheese.jfif",
  "tub-plain-cc": "data/Plain Cream Cheese Tub.jfif",
  "tub-flavored-cc": "data/Flavored Cream Cheese Tub.jfif",
  "tub-plain-butter": "data/Plain Butter Tub.jfif",
  "tub-flavored-butter": "data/Flavored Butter Tub.jfif",
  "tub-jelly": "data/Jelly Tub.jfif",
  "lox-quarter": "data/Lox Slices (1 upon 4 lb.).jfif",
  "lox-half": "data/Lox Slices (1 upon 2 lb).jfif",
  "lox-pound": "data/Lox Slices (1 lb.).jfif",
  "bakery-muffin": "data/Jumbo Muffins.jpg",
  "bakery-cookie": "data/Jumbo Cookies.jpg",
  "bakery-crumb-cake": "data/Crumb Cake.jpg",
  "bakery-brownie": "data/Brownie.jpg",
  "bakery-blondie": "data/Blondie.jfif",
  "burrito-1": "data/#1 Burrito.jpg",
  "burrito-2": "data/#2 Burrito.jfif",
  "burrito-3": "data/#3 Burrito.jfif",
  "bfast-quesadilla-4": "data/#4 Quesadilla.jfif",
  "bfast-quesadilla-5": "data/#5 Quesadilla.jfif",
  "bfast-quesadilla-6": "data/#6 Quesadilla.jfif",
  "bfast-egg": "data/Egg Sandwich.jpg",
  "bfast-egg-cheese": "data/Egg & Cheese Sandwich.jpg",
  "bfast-egg-meat-cheese": "data/Egg, Meat & Cheese Sandwich.jpg",
  "bfast-meat-egg": "data/Meat & Egg Sandwich.jpg",
  "bfast-belly-buster": "data/Belly Buster Sandwich.jpg",
  "bfast-buddy-buster": "data/Buddy Buster Sandwich.jpg",
  "bfast-breakfast-bomb": "data/Breakfast Bomb Sandwich.jpg",
  "bfast-western-patty": "data/Western Patty Sandwich.jpg",
  "bfast-philly": "data/Philly Sandwich.jpg",
  "bfast-healthy-veggie": "data/Healthy Veggie Sandwich.jpg",
  "bfast-xxx": "data/XXX Sandwich.jpg",
  "bfast-leo": "data/The Leo Sandwich.jpg",
  "bfast-avocado-toast": "data/Classic Avocado Toast.jpg",
  "omelette-3-eggs": "data/3 Eggs Any Style.jpg",
  "omelette-3-eggs-meat": "data/3 Eggs Any Style w Meat.jpg",
  "omelette-western": "data/The Western Omelette.jpg",
  "omelette-veggie": "data/The Veggie Omelette.jpg",
  "omelette-cheesy": "data/The Cheesy Omelette.jpg",
  "omelette-hammy": "data/Omelette.jpg",
  "omelette-bacon": "data/Bacon Lovers Omelette.jpg",
  "omelette-shroomy": "data/The Shroomy Omelette.jpg",
  "omelette-mediterranean": "data/The Mediterranean Omelette.jpg",
  "omelette-turkey-garden": "data/The Turkey Garden Omelette.jpg",
  "pancakes-buttermilk": "data/3 Buttermilk Pancakes.jpg",
  "pancakes-chocolate": "data/3 Chocolate Chip Pancakes.jpg",
  "pancakes-blueberry": "data/3 Blueberry Pancakes.jpg",
  "pancakes-cinnamon": "data/3 Cinnamon Swirl Pancakes.jpg",
  "ft-classic": "data/Classic French Toast.jpg",
  "ft-nutella-smores": "data/Nutella Smores French Toast.jpg",
  "ft-strawberry": "data/Strawberry Stuffed French Toast.jpg",
  "ft-oreo": "data/Once Stuffed French Toast.jpg",
  "side-home-fries": "data/Seasoned Home Fries.jpg",
  "side-silver-dollar": "data/Silver Dollar Fries (Chips).jpg",
  "side-hash-patty": "data/Hash Brown Patty.jpg",
  "side-breakfast-meat": "data/Side of Breakfast Meat.jpg",
  "side-cream-cheese": "data/Side of Cream Cheese.jpg",
  "side-fruit-salad": "data/Fruit Salad.jpg",
  "side-watermelon": "data/Watermelon.jpg",
  "side-chobani": "data/Chobani Yogurt.jpg",
  "salad-garden": "data/Perfect Garden Salad.jpg",
  "salad-cobb": "data/Chopped Cobb Salad.jpg",
  "salad-green-dream": "data/Green Dream Salad.jpg",
  "salad-caesar": "data/Caesar Salad.jpg",
  "salad-greek": "data/Chopped Greek Salad.jpg",
  "deli-tuna": "data/White Tuna Salad (1 upon 4 lb).jfif",
  "deli-veggie-tuna": "data/Low Fat Veggie Tuna Salad( 1 upon 4 lb).jpg",
  "deli-chicken": "data/White Chicken Salad( 1 upon 4 lb ).jpg",
  "deli-cranberry-chicken": "data/Cranberry Walnut Chicken Salad( 1 upon 4 lb ).jpg",
  "deli-shrimp": "data/Shrimp Salad ( 1 upon 4 lb ).jpg",
  "deli-egg": "data/Egg Salad (1 upon 4 lb).jpg",
  "deli-whitefish": "data/Whitefish Salad (1 upon 4 lb).jpg",
  "deli-salmon": "data/Baked Salmon Salad (1 upon 4 lb).jpg",
  "hot-grilled-chicken": "data/Grilled Chicken Sandwich.jpg",
  "hot-chicken-blt": "data/Chicken BLT Sandwich.jpg",
  "hot-chicken-mozzarella": "data/Grilled Chicken, Roasted Peppers & Mozzarella Sandwich.jpg",
  "hot-crispy-chicken": "data/Crispy Chicken Sandwich.jpg",
  "hot-spicy-crispy": "data/Spicy Crispy Chicken Sandwich.jpg",
  "hot-grilled-cheese": "data/Grilled Cheese Sandwich.jpg",
  "hot-grilled-cheese-blt": "data/Grilled Cheese w Bacon & Tomato Sandwich.jpg",
  "hot-blt": "data/BLT Sandwich.jpg",
  "spec-cuban": "data/#1 The Cuban.jpg",
  "spec-reuben": "data/#2 The Reuben.jpg",
  "spec-gourmet-blt": "data/#3 The Gourmet BLT.jpg",
  "spec-beef-gyro": "data/#4 The Beef Gyro.jpg",
  "spec-gourmet-grilled-cheese": "data/#5 The Gourmet Grilled Cheese.jpg",
  "spec-tuna-melt": "data/#6 Tuna Melt.jpg",
  "spec-sloppy-joe": "data/#7 The Sloppy Joe.jpg",
  "spec-turkey-club": "data/#8 The Turkey Club.jpg",
  "spec-pastrami-corned": "data/#9 The Pastrami & Corned Beef.jpg",
  "spec-cranberry": "data/#10 The Cranberry.jpg",
  "sub-philly": "data/Philly Cheesesteak Sub.jpg",
  "sub-chicken-philly": "data/Chicken Cheesesteak Sub.jpg",
  "sub-crispy-blt": "data/Crispy Chicken BLT Sub.jpg",
  "sub-buffalo-chicken": "data/Crispy Buffalo Chicken Sub.jpg",
  "hoagie-1": "data/#1 Ham & Cheese Sandwich.jpg",
  "hoagie-2": "data/#2 Ham, Salami & Cheese Sandwich.jpg",
  "hoagie-3": "data/#3 Ham, Turkey & Cheese Sandwich.jpg",
  "hoagie-4": "data/#4 Turkey & Cheese Sandwich.jpg",
  "hoagie-5": "data/#5 Italian Sandwich.jpg",
  "hoagie-6": "data/#6 American Sandwich.jpg",
  "hoagie-7": "data/#7 Sloppy Sandwich.jpg",
  "hoagie-8": "data/#8 Corned Beef & Pastrami Sandwich.jpg",
  "hoagie-9": "data/#9 Roast Beef & Cheese Sandwich.jpg",
  "hoagie-10": "data/#10 Bologna & Cheese Sandwich.jpg",
  "hoagie-11": "data/#11 Liverwurst Sandwich.jpg",
  "hoagie-12": "data/#12 Honey Maple Turkey & Cheese Sandwich.jpg",
  "salad-sand-tuna": "data/#13 White Tuna Sandwich.jpg",
  "salad-sand-veggie-tuna": "data/#14 Low Fat Veggie Tuna Sandwich.jpg",
  "salad-sand-chicken": "data/#15 White Chicken Salad Sandwich.jpg",
  "salad-sand-cranberry": "data/#16 Cranberry Walnut Chicken Salad Sandwich.jpg",
  "salad-sand-shrimp": "data/#17 Shrimp Salad Sandwich.jpg",
  "salad-sand-egg": "data/#18 Egg Salad Sandwich.jpg",
  "salad-sand-whitefish": "data/#19 Whitefish Salad Sandwich.jpg",
  "salad-sand-salmon": "data/#20 Baked Salmon Salad Sandwich.jpg",
  "veg-all-veggies": "data/#21 All Fresh Veggies Sandwich.jpg",
  "veg-cheese-combo": "data/#22 Veggie & Cheese Combo Sandwich.jpg",
  "panini-1": "data/#1 Honey Maple Turkey Panini.jpg",
  "panini-2": "data/#2 Italian Combo Panini.jpg",
  "panini-3": "data/#3 Cali Turkey Panini.jpg",
  "panini-4": "data/#4 Chipotle Grilled Chicken Panini.jpg",
  "panini-5": "data/#5 BBQ Chicken Panini.jpg",
  "wrap-hot-1": "data/#1 Balsamic Chicken Wrap.jpg",
  "wrap-hot-2": "data/#2 Crispy Honey Chicken Wrap.jpg",
  "wrap-hot-3": "data/#3 Cali Chicken Grilled Wrap.jpg",
  "wrap-hot-4": "data/#4 Crispy Buffalo Chicken Wrap.jpg",
  "wrap-hot-5": "data/#5 Grilled Chicken Caesar Wrap.jpg",
  "wrap-cold-6": "data/#6 Turkey BLT Wrap.jpg",
  "wrap-cold-7": "data/#7 New Yorker Wrap.jpg",
  "wrap-cold-8": "data/#8 Light Veggie Tuna Wrap.jpg",
  "wrap-cold-9": "data/#9 Cali Honey Turkey Wrap.jpg",
  "wrap-cold-10": "data/#10 Chicken Salad BLT Wrap.jpg",
  "quesadilla-cheese": "data/Cheese Quesadilla.jpg",
  "quesadilla-chicken": "data/Chicken & Cheese Quesadilla.jpg",
  "quesadilla-chicken-bacon": "data/Chicken, Bacon & Ranch Quesadilla.jpg",
  "quesadilla-buffalo": "data/Buffalo Chicken Ranch Quesadilla.jpg",
  "burger-cheese": "data/Cheeseburger.jpg",
  "burger-bacon": "data/Bacon Cheeseburger.jpg",
  "burger-turkey": "data/Turkey Cheeseburger.jpg",
  "burger-mushroom-swiss": "data/Mushroom Swiss Burger.jpg",
  "burger-breakfast": "data/Breakfast Burger.jpg",
  "burger-avocado": "data/Avocado Burger.jpg",
  "burger-chipotle": "data/Chipotle Burger.jpg",
  "burger-kosher-deli": "data/Kosher Deli Burger.jpg",
  "hotdog-beef": "data/All Beef Hot Dog.jpg",
  "hotdog-italian": "data/Italian Hot Dog.jpg",
  "side-fries": "data/French Fries.jpg",
  "side-onion-rings": "data/Onion Rings.jpg",
  "side-tenders-3": "data/Chicken Tenders (3).jpg",
  "side-tenders-5": "data/Chicken Tenders (5).jpg",
  "side-wings-6": "data/Buffalo Wings (6).jpg",
  "side-wings-12": "data/Buffalo Wings (12).jpg",
  "bev-iced-tea": "data/Fresh Brewed Iced Tea.jpg",
  "bev-iced-tea-flavored": "data/Flavored Fresh Brewed Iced Tea.jpg",
  "bev-lemonade": "data/Fresh Lemonade.jpg",
  "bev-lemonade-flavored": "data/Flavored Fresh Lemonade.jpg",
  "bev-smoothie": "data/Fruit Smoothies.jpg",
  "bev-canned-soda": "data/Canned Soda.jpg",
  "bev-bottled-soda": "data/Bottled Soda (20 oz.).jpg",
  "bev-snapple": "data/Snapple (16oz.).jfif",
  "bev-gatorade": "data/Gatorade.jfif",
  "bev-arizona": "data/Arizona (20oz.).jfif",
  "bev-vitamin-water": "data/Vitamin Water.jpg",
  "bev-monster": "data/Monster.jfif",
  "bev-bang": "data/Bang 4.25.jfif",
  "bev-bang-alt": "data/Bang 4.49.jfif",
  "bev-bai": "data/Bai.jfif",
  "bev-calypso": "data/calypso.jfif",
  "bev-poland-sparkling": "data/Poland Spring Sparkling Water.jfif",
  "bev-tropicana-12": "data/Tropicana (12oz.).jfif",
  "bev-tropicana-16": "data/Tropicana (16oz.).jfif",
  "bev-tropicana-gallon": "data/Tropicana Orange Juice (Gallon).jfif",
  "bev-choc-milk-16": "data/Cream o Land Chocolate Milk (16oz).jfif",
  "bev-choc-milk-quart": "data/Cream o Land Chocolate Milk (quart).jfif",
  "bev-nesquik": "data/Nesquik.jfif",
  "bev-yoohoo": "data/Yoohoo.jfif",
  "bev-red-bull": "data/Red Bull.jfif",
  "bev-red-bull-diet": "data/Diet Red Bull (8oz).jfif",
  "bev-sbux-frap-95": "data/Starbucks Frappuccino Coffee Flavor (9.5 oz).jfif",
  "bev-sbux-frap-13": "data/Starbucks Frappuccino (13oz).jfif",
  "bev-sbux-double": "data/Starbucks Double Shot.jfif",
  "bev-poland-water": "data/Poland Spring Bottled Water.jfif",
  "bev-fiji": "data/Fiji Water.jfif",
  "bev-essentia": "data/Essentia Water.jfif"
};

  function encodeDataPath(path) {
    const slash = path.lastIndexOf("/");
    if (slash === -1) return encodeURIComponent(path);
    return path.slice(0, slash + 1) + encodeURIComponent(path.slice(slash + 1));
  }

  function getMenuImage(key) {
    const path = IMAGE_MAP[key] || PLACEHOLDER;
    return encodeDataPath(path) + "?v=" + CACHE_VERSION;
  }

  function getMenuImageMeta(imageKey) {
    return {
      src: getMenuImage(imageKey),
      width: W,
      height: H,
      loading: "lazy",
    };
  }

  window.MENU_IMAGES = {
    width: W,
    height: H,
    cacheVersion: CACHE_VERSION,
    placeholder: encodeDataPath(PLACEHOLDER) + "?v=" + CACHE_VERSION,
    map: IMAGE_MAP,
    get: getMenuImage,
    meta: getMenuImageMeta,
  };
})();
