/** One-off audit: compare generate-menu.mjs output vs official menu prices */
import { readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const mod = await import("./generate-menu.mjs?dummy").catch(() => null);

// Official menu: name -> { price, desc? }
const OFFICIAL = {
  "Coffee": "$2.50",
  "Single Espresso": "$1.77",
  "Double Espresso": "$3.14",
  "Hot Cappuccino": "$3.14",
  "Flavored Hot Cappuccino": "$3.14",
  "Iced Latte": "$3.14",
  "Flavored Iced Latte": "$2.99",
  "Iced Coffee": "$3.66",
  "Flavored Iced Coffee": "$3.66",
  "Frozen Frappe": "$5.24",
  "Flavored Frozen Frappe": "$5.24",
  "Box o Joe (12 Cups)": "$26.24",
  "Bagel (1)": "$1.77",
  "Bagels (6)": "$9.96",
  "Bagel (13)": "$19.94",
  "#1 Bagel Special": "$27.29",
  "#2 Bagel Special": "$28.34",
  "Bagel w/ Butter": "$3.41",
  "Bagel w/ Cinna Butter": "$3.66",
  "Bagel w/ Peanut Butter": "$3.56",
  "Bagel w/ Nutella": "$3.56",
  "Bagel w/ Jelly": "$3.41",
  "Bagel w/ Plain Cream Cheese": "$4.08",
  "Bagel w/ Vegetable Cream Cheese": "$5.13",
  "Bagel w/ Scallion Cream Cheese": "$5.13",
  "Bagel w/ Lox Spread": "$6.29",
  "Bagel w/ Walnut Raisin Cream Cheese": "$5.13",
  "Bagel w/ Strawberry Cream Cheese": "$5.13",
  "Bagel w/ Jalapeno Garlic Cream Cheese": "$5.13",
  "Bagel w/ Oreo Explosion Cream Cheese": "$5.13",
  "Bagel w/ Bacon & Chives Cream Cheese": "$5.13",
  "Bagel w/ Lite Veggie Cream Cheese": "$5.13",
  "Bagel w/ Green Olive Pimento Cream Cheese": "$5.13",
  "Bagel w/ Lox & Plain Cream Cheese": "$12.06",
  "Bagel w/ Lox & Veggie Cream Cheese": "$13.11",
  "Bagel w/ Lox & Scallion Cream Cheese": "$13.11",
  "Bagel w/ Whitefish Salad & Plain Cream Cheese": "$15.21",
  "Plain Cream Cheese Tub": "$6.30",
  "Flavored Cream Cheese Tub": "$7.35",
  "Plain Butter Tub": "$5.78",
  "Flavored Butter Tub": "$3",
  "Jelly Tub": "$5.78",
  "Lox Slices (1/4 lb.)": "$10.50",
  "Lox Slices (1/2 lb.)": "$20.99",
  "Lox Slices (1 lb.)": "$41.99",
  "Jumbo Muffins": "$3.41",
  "Jumbo Cookies": "$3.41",
  "Crumb Cake": "$3.41",
  "Brownie": "$3.41",
  "Blondie": "$3.41",
  "#1 Burrito": "$7.34",
  "#2 Burrito": "$8.39",
  "#3 Burrito": "$8.39",
  "#4 Quesadilla": "$7.34",
  "#5 Quesadilla": "$7.34",
  "#6 Quesadilla": "$8.39",
  "Egg Sandwich": "$4.46",
  "Egg & Cheese Sandwich": "$4.99",
  "Egg, Meat & Cheese Sandwich": "$7.61",
  "Meat & Egg Sandwich": "$6.92",
  "Belly Buster Sandwich": "$9.96",
  "Buddy Buster Sandwich": "$9.44",
  "Breakfast Bomb Sandwich": "$8.60",
  "Western Patty Sandwich": "$9.44",
  "Philly Sandwich": "$8.39",
  "Healthy Veggie Sandwich": "$7.86",
  "XXX Sandwich": "$10.49",
  "The Leo Sandwich": "$9.44",
  "Classic Avocado Toast": "$6.29",
  "3 Eggs Any Style": "$6.56",
  "3 Eggs Any Style w/ Meat": "$8.91",
  "The Western Omelette": "$9.44",
  "The Veggie Omelette": "$8.39",
  "The Cheesy Omelette": "$8.39",
  "The Hammy Omelette": "$8.91",
  "The Bacon Lovers Omelette": "$9.44",
  "The Shroomy Omelette": "$8.39",
  "The Mediterranean Omelette": "$9.44",
  "The Turkey Garden Omelette": "$9.96",
  "3 Buttermilk Pancakes": "$7.34",
  "3 Chocolate Chip Pancakes": "$8.66",
  "3 Blueberry Pancakes": "$8.66",
  "3 Cinnamon Swirl Pancakes": "$8.39",
  "Classic French Toast": "$8.39",
  "Nutella Smores French Toast": "$9.71",
  "Strawberry Stuffed French Toast": "$9.71",
  "Once Stuffed French Toast": "$9.71",
  "Seasoned Home Fries": "$5.20",
  "Silver Dollar Fries (Chips)": "$5.20",
  "Hash Brown Patty": "$2.09",
  "Side of Breakfast Meat": "$3.41",
  "Side of Cream Cheese": "$2.09",
  "Fruit Salad": "$3.25",
  "Watermelon": "$3.25",
  "Chobani Yogurt": "$1.99",
  "Perfect Garden Salad": "$8.14",
  "Chopped Cobb Salad": "$9.44",
  "Green Dream Salad": "$9.44",
  "Caesar Salad": "$8.14",
  "Chopped Greek Salad": "$8.14",
  "White Tuna Salad (1/4 lb)": "$3.15",
  "Low Fat Veggie Tuna Salad (1/4 lb)": "$3.41",
  "White Chicken Salad (1/4 lb)": "$3.15",
  "Cranberry Walnut Chicken Salad (1/4 lb)": "$3.68",
  "Shrimp Salad (1/4 lb)": "$3.94",
  "Egg Salad (1/4 lb)": "$2.89",
  "Whitefish Salad (1/4 lb)": "$4.73",
  "Baked Salmon Salad (1/4 lb)": "$4.73",
  "Grilled Chicken Sandwich": "$8.66",
  "Chicken BLT Sandwich": "$10.49",
  "Grilled Chicken, Roasted Peppers & Mozzarella Sandwich": "$9.96",
  "Crispy Chicken Sandwich": "$9.44",
  "Spicy Crispy Chicken Sandwich": "$9.44",
  "Grilled Cheese Sandwich": "$6.81",
  "Grilled Cheese w/ Bacon & Tomato Sandwich": "$8.66",
  "BLT Sandwich": "$7.86",
  "#1 The Cuban": "$9.71",
  "#2 The Reuben": "$9.71",
  "#3 The Gourmet BLT": "$9.71",
  "#4 The Beef Gyro": "$8.66",
  "#5 The Gourmet Grilled Cheese": "$9.71",
  "#6 Tuna Melt": "$9.44",
  "#7 The Sloppy Joe": "$11.54",
  "#8 The Turkey Club": "$11.54",
  "#9 The Pastrami & Corned Beef": "$10.49",
  "#10 The Cranberry": "$10.49",
  "Philly Cheesesteak Sub": "$9.71",
  "Chicken Cheesesteak Sub": "$9.71",
  "Crispy Chicken BLT Sub": "$11.01",
  "Crispy Buffalo Chicken Sub": "$9.96",
  "#1 Ham & Cheese Sandwich": "$9.44",
  "#2 Ham, Salami & Cheese Sandwich": "$9.44",
  "#3 Ham, Turkey & Cheese Sandwich": "$9.96",
  "#4 Turkey & Cheese Sandwich": "$9.96",
  "#5 Italian Sandwich": "$9.96",
  "#6 American Sandwich": "$10.49",
  "#7 Sloppy Sandwich": "$11.01",
  "#8 Corned Beef & Pastrami Sandwich": "$10.49",
  "#9 Roast Beef & Cheese Sandwich": "$10.49",
  "#10 Bologna & Cheese Sandwich": "$9.44",
  "#11 Liverwurst Sandwich": "$8.39",
  "#12 Honey Maple Turkey & Cheese Sandwich": "$9.96",
  "#13 White Tuna Sandwich": "$8.91",
  "#14 Low Fat Veggie Tuna Sandwich": "$9.44",
  "#15 White Chicken Salad Sandwich": "$8.91",
  "#16 Cranberry Walnut Chicken Salad Sandwich": "$9.44",
  "#17 Shrimp Salad Sandwich": "$9.44",
  "#18 Egg Salad Sandwich": "$7.61",
  "#19 Whitefish Salad Sandwich": "$10.49",
  "#20 Baked Salmon Salad Sandwich": "$10.49",
  "#21 All Fresh Veggies Sandwich": "$7.86",
  "#22 Veggie & Cheese Combo Sandwich": "$8.91",
  "#1 Honey Maple Turkey Panini": "$9.71",
  "#2 Italian Combo Panini": "$9.71",
  "#3 Cali Turkey Panini": "$9.71",
  "#4 Chipotle Grilled Chicken Panini": "$9.71",
  "#5 BBQ Chicken Panini": "$9.71",
  "#1 Balsamic Chicken Wrap": "$9.44",
  "#2 Crispy Honey Chicken Wrap": "$10.49",
  "#3 Cali Chicken Grilled Wrap": "$11.54",
  "#4 Crispy Buffalo Chicken Wrap": "$9.44",
  "#5 Grilled Chicken Caesar Wrap": "$9.44",
  "#6 Turkey BLT Wrap": "$10.49",
  "#7 New Yorker Wrap": "$10.49",
  "#8 Light Veggie Tuna Wrap": "$8.66",
  "#9 Cali Honey Turkey Wrap": "$11.54",
  "#10 Chicken Salad BLT Wrap": "$10.49",
  "Cheese Quesadilla": "$7.34",
  "Chicken & Cheese Quesadilla": "$9.44",
  "Chicken, Bacon & Ranch Quesadilla": "$10.49",
  "Buffalo Chicken Ranch Quesadilla": "$9.44",
  "Cheeseburger": "$8.49",
  "Bacon Cheeseburger": "$10.49",
  "Turkey Cheeseburger": "$8.91",
  "Mushroom Swiss Burger": "$9.44",
  "Breakfast Burger": "$11.54",
  "Avocado Burger": "$10.49",
  "Chipotle Burger": "$11.54",
  "Kosher Deli Burger": "$11.54",
  "All Beef Hot Dog": "$3.66",
  "Italian Hot Dog": "$6.29",
  "French Fries": "$4.46",
  "Onion Rings": "$4.71",
  "Chicken Tenders (3)": "$6.81",
  "Chicken Tenders (5)": "$8.91",
  "Buffalo Wings (6)": "$7.86",
  "Buffalo Wings (12)": "$12.59",
  "Fresh Brewed Iced Tea": "$2.61",
  "Flavored Fresh Brewed Iced Tea": "$2.61",
  "Fresh Lemonade": "$3.14",
  "Flavored Fresh Lemonade": "$3.14",
  "Fruit Smoothies": "$5.24",
  "Canned Soda": "$1.39",
  "Bottled Soda (20 oz.)": "$2.75",
  "Snapple (16oz.)": "$2.75",
  "Gatorade": "$2.75",
  "Arizona (20oz.)": "$2.75",
  "Vitamin Water": "$2.49",
  "Monster": "$4.25",
  "Bang": "$4.25",
  "Bai": "$3.49",
  "Calypso": "$3.49",
  "Poland Spring Sparkling Water": "$1.99",
  "Tropicana (12oz.)": "$2.49",
  "Tropicana (16oz.)": "$2.75",
  "Tropicana Orange Juice (Gallon)": "$5.99",
  "Cream o Land Chocolate Milk (16oz)": "$2.49",
  "Cream o Land Chocolate Milk (quart)": "$3.25",
  "Nesquik": "$2.75",
  "Yoohoo": "$2.25",
  "Red Bull": "$3.49",
  "Diet Red Bull (8oz)": "$3.49",
  "Starbucks Frappuccino Coffee Flavor (9.5 oz)": "$3.49",
  "Starbucks Frappuccino (13oz)": "$4.49",
  "Starbucks Double Shot": "$4.49",
  "Poland Spring Bottled Water": "$1.79",
  "Fiji Water": "$2.25",
  "Essentia Water": "$2.25",
};

const raw = readFileSync(join(root, "js/menu-data.js"), "utf8");
const cats = JSON.parse(raw.replace(/^[\s\S]*?=\s*/, "").replace(/;\s*$/, ""));

const mismatches = [];
const missing = [];
const extra = new Set(Object.keys(OFFICIAL));

for (const cat of cats) {
  for (const it of cat.items) {
    extra.delete(it.name);
    const official = OFFICIAL[it.name];
    if (!official) {
      // try alternate names
      const alt = Object.keys(OFFICIAL).find((k) => k.replace(/\s+/g, " ") === it.name.replace(/\s+/g, " "));
      if (!alt) missing.push({ name: it.name, price: it.price, cat: cat.label });
      else if (alt !== it.name) mismatches.push({ type: "name", have: it.name, want: alt, price: it.price });
      else if (it.price !== OFFICIAL[alt]) mismatches.push({ type: "price", name: it.name, have: it.price, want: OFFICIAL[alt] });
    } else if (it.price !== official && it.price !== official.replace("$3", "$3.00")) {
      mismatches.push({ type: "price", name: it.name, have: it.price, want: official });
    }
  }
}

console.log("Mismatches:", mismatches.length);
mismatches.forEach((m) => console.log(m));
console.log("Missing from official:", missing.length);
missing.forEach((m) => console.log(m));
console.log("Extra in official not in menu:", [...extra]);
